services:
    dtc_queue.document_manager:
        synthetic: true

    dtc_queue.entity_manager:
        synthetic: true

    dtc_queue.job_manager:
        synthetic: true

    dtc_queue.run_manager:
        synthetic: true

    dtc_queue.run_manager.mongodb: # deprecated, remove in 4.0
        alias: dtc_queue.run_manager.odm

    dtc_queue.run_manager.odm:
        class: Dtc\QueueBundle\ODM\RunManager
        arguments:
            - "@dtc_queue.document_manager"
            - "%dtc_queue.class_run%"
            - "%dtc_queue.class_job_timing%"
            - "%dtc_queue.record_timings%"
        calls:
            - ["setRunArchiveClass", ["%dtc_queue.class_run_archive%"]]

    dtc_queue.grid_source.live_jobs.odm:
        class: Dtc\QueueBundle\ODM\LiveJobGridSource
        arguments:
            - "@dtc_queue.job_manager.odm"
        calls:
            - [ 'setAnnotationReader', ['@annotation_reader' ]]
            - [ 'setCacheDir', ['%kernel.cache_dir%' ]]

    dtc_queue.grid_source.live_jobs.orm:
        class: Dtc\QueueBundle\ORM\LiveJobGridSource
        arguments:
            - "@dtc_queue.job_manager.orm"
        calls:
            - [ 'setAnnotationReader', ['@annotation_reader' ]]
            - [ 'setCacheDir', ['%kernel.cache_dir%' ]]

    dtc_queue.job_manager.mongodb: # deprecated, remove in 4.0
        alias: dtc_queue.job_manager.odm

    dtc_queue.job_manager.odm:
        class: Dtc\QueueBundle\ODM\JobManager
        arguments:
            - '@dtc_queue.document_manager'
            - '%dtc_queue.class_job%'
            - '%dtc_queue.class_job_archive%'
            - '%dtc_queue.class_run%'
            - '%dtc_queue.class_run_archive%'
        calls:
            - ["setMaxPriority", ['%dtc_queue.priority_max%']]
            - ["setPriorityDirection", ['%dtc_queue.priority_direction%']]

    dtc_queue.job_manager.beanstalkd:
        class: Dtc\QueueBundle\Beanstalkd\JobManager
        arguments:
            - '%dtc_queue.class_job%'

    dtc_queue.job_manager.rabbit_mq:
        class: Dtc\QueueBundle\RabbitMQ\JobManager
        calls:
            - ["setMaxPriority", ['%dtc_queue.priority_max%']]
            - ["setPriorityDirection", ['%dtc_queue.priority_direction%']]

    dtc_queue.run_manager.orm:
        class: Dtc\QueueBundle\ORM\RunManager
        arguments:
            - '@dtc_queue.entity_manager'
            - "%dtc_queue.class_run%"
            - "%dtc_queue.class_job_timing%"
            - "%dtc_queue.record_timings%"
        calls:
            - ["setRunArchiveClass", ["%dtc_queue.class_run_archive%"]]

    dtc_queue.run_manager.beanstalkd:
        alias: dtc_queue.run_manager_base

    dtc_queue.run_manager.rabbit_mq:
        alias: dtc_queue.run_manager_base

    dtc_queue.run_manager_base:
        class: Dtc\QueueBundle\Model\RunManager
        arguments:
            - "%dtc_queue.class_run%"
            - "%dtc_queue.class_job_timing%"
            - "%dtc_queue.record_timings%"

    dtc_queue.job_manager.orm:
        class: Dtc\QueueBundle\ORM\JobManager
        arguments:
            - '@dtc_queue.entity_manager'
            - '%dtc_queue.class_job%'
            - '%dtc_queue.class_job_archive%'
            - '%dtc_queue.class_run%'
            - '%dtc_queue.class_run_archive%'
        calls:
            - ["setMaxPriority", ['%dtc_queue.priority_max%']]
            - ["setPriorityDirection", ['%dtc_queue.priority_direction%']]

    dtc_queue.worker_manager:
        class: Dtc\QueueBundle\Model\WorkerManager
        arguments:
            - '@dtc_queue.job_manager'
            - '@dtc_queue.event_dispatcher'
        calls:
            - [ "setLogger", ['@?logger'] ]
        tags: [{ name: monolog.logger, channel: dtc_queue }]

    dtc_queue.event_dispatcher:
        class: Dtc\QueueBundle\EventDispatcher\EventDispatcher
    dtc_queue.remove_listener:
        class: Dtc\QueueBundle\Doctrine\DtcQueueListener
        arguments:
            - '%dtc_queue.class_job_archive%'
            - '%dtc_queue.class_run_archive%'
        tags:
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine_mongodb.odm.event_listener, event: preRemove }
            - { name: doctrine_mongodb.odm.event_listener, event: perPersist }
            - { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
    dtc_queue.run.loop:
        class: Dtc\QueueBundle\Run\Loop
        arguments:
            - "@dtc_queue.worker_manager"
            - "@dtc_queue.job_manager"
            - "@dtc_queue.run_manager"
        calls:
            - [ "setLogger", ['@?logger'] ]
        tags: [{ name: monolog.logger, channel: dtc_queue }]
