services:
    dtc_queue.document_manager:
        synthetic: true

    dtc_queue.job_manager.mongodb:
        class: Dtc\QueueBundle\Documents\JobManager
        arguments:
            - '@dtc_queue.document_manager'
            - '%dtc_queue.job_class%'

    dtc_queue.job_manager.beanstalkd:
        class: Dtc\QueueBundle\Beanstalkd\JobManager
        arguments:
            - '%dtc_queue.job_class%'

    dtc_queue.job_manager.rabbit_mq:
        class: Dtc\QueueBundle\RabbitMQ\JobManager

    dtc_queue.job_manager.orm:
        class: Dtc\QueueBundle\ORM\JobManager
        arguments:
            - '@dtc_queue.entity_manager'
            - '%dtc_queue.job_class%'

    dtc_queue.worker_manager:
        class: Dtc\QueueBundle\Model\WorkerManager
        arguments:
            - '@dtc_queue.job_manager'
            - '@dtc_queue.event_dispatcher'
            - '@logger='
        tags: [{ name: monolog.logger, channel: dtc_queue }]

    dtc_queue.event_dispatcher:
        class: Dtc\QueueBundle\EventDispatcher\EventDispatcher
